language: node_js
deploy:
  api_key: df85fbb2-f468-4c37-b380-c795d6c44bd5
  email: tselentispanagis@gmail.com
  provider: npm
  on:
    tags: true

node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4.0"
  - "4.1"
  - "4.2"
  - "5.0"

services:
  - mysql

before_script:

notifications:
  email: true

# whitelisted branches
branches:
  only:
    - master